--JOB DATABASE

--Table For Job with Foreign Key-> USERID

CREATE TABLE JOB
(
	HE_JOBID INT IDENTITY(1,1),
	USERID INT,
	JOB_TITLE VARCHAR(25),
	COMPANY_NAME VARCHAR(30),
	SALARY VARCHAR (50),
	JOB_NATURE VARCHAR(15),
	COMAPNY_WEBSITE VARCHAR(30),
	COMAPNY_EMAIL VARCHAR(30),
	JOB_CATEGORY VARCHAR(30),
	JOB_DESC VARCHAR(100),
)

-- ADDING SALARY COLOUMN

ALTER TABLE JOB
ADD SALARY VARCHAR(50);

-- ADDING SALARY COLOUMN

ALTER TABLE JOB
ADD APPLY_LINK VARCHAR(100);


--get all job data from database

CREATE PROCEDURE SP_GETALLJOBDATA
AS
BEGIN
SELECT * FROM JOB
END

--POST A JOB SP SP_POSTAJOB

CREATE PROCEDURE SP_POSTAJOB
(
	@Userid Int,
	@Jobtitle VARCHAR(30),
	@Compname VARCHAR(30),
	@Location VARCHAR(30),
	@Jobnature VARCHAR(30),
	@Compweb VARCHAR(30),
	@Compemail VARCHAR(30),
	@Jobct VARCHAR(30),
	@Jobdesc VARCHAR(100),
	@Salary VARCHAR(50),
	@ApplyLink VARCHAR(30)
)
AS
BEGIN
	INSERT INTO JOB
	VALUES
	(
		@Userid,
		@Jobtitle,
		@Compname,
		@Location,
		@Jobnature,
		@Compweb,
		@Compemail,
		@Jobct,
		@Jobdesc,
		@Salary,
		@ApplyLink
	)
END

-- STORED PROCEDURE TO GET JOB DETAILS BY HE_JOBID

CREATE PROCEDURE SP_GETJOBDATA_BYID
(
	@heid int
)
AS
BEGIN
SELECT * FROM JOB WHERE HE_JOBID=@heid;
END